
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bc
 */
public class cGui extends javax.swing.JFrame {

    private final cPenjat penjat;
    private String chars;

    /**
     * Creates new form cGui
     */
    public cGui() {
        initComponents();
        setLocationRelativeTo(null);
        penjat = new cPenjat();
        chars = "";
        lblPos.setText(penjat.pintaEspais());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPos = new javax.swing.JLabel();
        txtErrorChars = new javax.swing.JTextField();
        btnComp = new javax.swing.JButton();
        txtChar = new javax.swing.JTextField();
        lblIntents = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblPos.setText("_ _ _ _ _ _");

        txtErrorChars.setEditable(false);
        txtErrorChars.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorChars.setFocusTraversalKeysEnabled(false);
        txtErrorChars.setFocusable(false);

        btnComp.setText("Comprovar");
        btnComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompActionPerformed(evt);
            }
        });

        lblIntents.setText("12 intents");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorcado01.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusTraversalKeysEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);

        jMenu1.setText("Nou joc");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sortir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComp))
                    .addComponent(txtErrorChars, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPos)
                    .addComponent(lblIntents))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblPos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtErrorChars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComp)
                            .addComponent(txtChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(lblIntents))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Segur que vols sortir?");
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        displayNewGame();
        displayEspais();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void displayEspais() {
        SwingUtilities.invokeLater(() -> {
            lblPos.setText(penjat.getPintat());
        });
    }

    private void displayNewGame() {
        int resposta = JOptionPane.showConfirmDialog(null, "Vols iniciar una nova partida?");
        if (resposta == JOptionPane.YES_OPTION) {
            penjat.nouJoc();
            txtChar.setText("");
            txtErrorChars.setText("");
            chars="";
            lblIntents.setText(penjat.getIntents() + " intents");
            btnComp.setEnabled(true);
            changeImg();
        }
    }

    private void displayError() {
        JOptionPane.showMessageDialog(this, "Mec format incorrecte");
    }
    private void displayGameOver() {
        JOptionPane.showMessageDialog(this, "Game Over: "+penjat.getParaula());
    }
    private void displayWin() {
        //JOptionPane.showMessageDialog(this, "Win");
        String player = JOptionPane.showInputDialog(this, "Win, enter your name:", "YEAH!!", JOptionPane.PLAIN_MESSAGE);
        penjat.guardarScore(player);
        btnComp.setEnabled(false);
    }

    private void btnCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompActionPerformed
        // TODO add your handling code here:
        if (checkGameOver()) {
            if (penjat.checkChar(txtChar.getText())) {
                if (penjat.lletraInParaula(txtChar.getText())) {
                    txtChar.setText("");
                    displayEspais();
                    checkWin();
                } else {
                    chars = chars + txtChar.getText().toUpperCase();
                    txtChar.setText("");
                    lblIntents.setText(penjat.getIntents() + " intents");
                    changeImg();
                    if(!checkGameOver()){
                        displayGameOver();
                    }
                }
            } else {
                displayError();
                txtChar.setText(null);
            }
            txtErrorChars.setText(chars);
        }
        else
            displayGameOver();
        txtChar.requestFocus();
    }//GEN-LAST:event_btnCompActionPerformed

    private void changeImg(){
        try {
            int app = penjat.getIntents();
            if(app<=5){
                lblIntents.setForeground(Color.red);
            }
            else
                lblIntents.setForeground(Color.black);
            int count = ((app-13)*(-1));
            String sCount ="";
            if(count<10){
                sCount="0"+count;
            }
            else
                sCount=""+count;
            String imagePath = "img/ahorcado"+sCount+".jpg";
            InputStream imgStream = cGui.class.getResourceAsStream(imagePath );
            BufferedImage myImg = ImageIO.read(imgStream);
            ImageIcon icon = new ImageIcon(myImg);
            jButton1.setIcon(icon);
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }
    private boolean checkGameOver() {
        return penjat.getIntents() != 0;
    }
    private boolean checkWin(){
        if(penjat.getWin()){
            displayWin();
            //omplir file scores
        }
        return penjat.getWin();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComp;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblIntents;
    private javax.swing.JLabel lblPos;
    private javax.swing.JTextField txtChar;
    private javax.swing.JTextField txtErrorChars;
    // End of variables declaration//GEN-END:variables
}
